GRANT SELECT ON Appointment to PUBLIC;
GRANT INSERT ON Appointment to PUBLIC;
GRANT DELETE ON Appointment to PUBLIC;
GRANT UPDATE ON Appointment to PUBLIC;

GRANT SELECT ON CareProvider to PUBLIC;
GRANT INSERT ON CareProvider to PUBLIC;
GRANT DELETE ON CareProvider to PUBLIC;
GRANT UPDATE ON CareProvider to PUBLIC;

GRANT SELECT ON Charge to PUBLIC;
GRANT INSERT ON Charge to PUBLIC;
GRANT DELETE ON Charge to PUBLIC;
GRANT UPDATE ON Charge to PUBLIC;

GRANT SELECT ON Patient to PUBLIC;
GRANT INSERT ON Patient to PUBLIC;
GRANT DELETE ON Patient to PUBLIC;
GRANT UPDATE ON Patient to PUBLIC;

GRANT SELECT ON CheckIn to PUBLIC;
GRANT INSERT ON CheckIn to PUBLIC;
GRANT DELETE ON CheckIn to PUBLIC;
GRANT UPDATE ON CheckIn to PUBLIC;

GRANT SELECT ON Service to PUBLIC;
GRANT INSERT ON Service to PUBLIC;
GRANT DELETE ON Service to PUBLIC;
GRANT UPDATE ON Service to PUBLIC;

GRANT SELECT ON Vaccine to PUBLIC;
GRANT INSERT ON Vaccine to PUBLIC;
GRANT DELETE ON Vaccine to PUBLIC;
GRANT UPDATE ON Vaccine to PUBLIC;
